# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# This has been commented out with a related jekyll 3 issue 2017.01.24
# relative_permalinks: true

# Setup
title:               Tonic
tagline:             '''s lesson learned'
description:         'Lessons learned in developing some useful things.'
url:                 https://jwkcp.github.io
baseurl:             ''

# gems: [jekyll-paginate]
# paginate:            5
# paginate_path: "page:num"

# About/contact
author:
  name:              Tony
  url:               http://jwgo.kr
  email:             jaewoong.go@gmail.com

# Custom vars
version:             1.0.0
motto:               'Keep looking, Don''t settle.'


gems: 
  - jekyll-paginate
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

paginate:            1
paginate_path: "page:num"

# DISQUS
page_url: jwkcp-github-io

# Conversion
markdown: kramdown
highlighter: rouge
